[package]
name = "context-service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
dotenv = "0.15"
hmac = "0.12"
sha2 = "0.10"
tokio = { version = "1", features = ["rt-multi-thread"] }